# Generated by Django 4.1.7 on 2023-04-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LRA2022",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.CharField(blank=True, max_length=16, null=True)),
                ("siteaddr", models.CharField(blank=True, max_length=254, null=True)),
                ("numunits", models.BigIntegerField(blank=True, null=True)),
                ("vacantland", models.CharField(blank=True, max_length=254, null=True)),
                ("numbldgs", models.BigIntegerField(blank=True, null=True)),
                ("landarea", models.BigIntegerField(blank=True, null=True)),
                ("frontage", models.FloatField(blank=True, null=True)),
                ("bdg1year", models.BigIntegerField(blank=True, null=True)),
                ("bdg1area", models.BigIntegerField(blank=True, null=True)),
                ("bdg1strycd", models.BigIntegerField(blank=True, null=True)),
                ("ward", models.BigIntegerField(blank=True, null=True)),
                ("policedist", models.BigIntegerField(blank=True, null=True)),
                ("zip", models.BigIntegerField(blank=True, null=True)),
                ("zoning", models.CharField(blank=True, max_length=254, null=True)),
                ("neighborho", models.CharField(blank=True, max_length=254, null=True)),
                ("landuse", models.CharField(blank=True, max_length=254, null=True)),
                ("point_x", models.FloatField(blank=True, null=True)),
                ("point_y", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "LRA_2022",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StLouisCityLandTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("land_id", models.CharField(blank=True, max_length=254, null=True)),
                ("owner", models.CharField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=254, null=True)),
                ("total", models.FloatField(blank=True, null=True)),
                ("handle", models.CharField(blank=True, max_length=16, null=True)),
                ("numunits", models.BigIntegerField(blank=True, null=True)),
                ("vacantland", models.CharField(blank=True, max_length=254, null=True)),
                ("numbldgs", models.BigIntegerField(blank=True, null=True)),
                ("landarea", models.BigIntegerField(blank=True, null=True)),
                ("frontage", models.FloatField(blank=True, null=True)),
                ("bdg1year", models.BigIntegerField(blank=True, null=True)),
                ("bdg1area", models.BigIntegerField(blank=True, null=True)),
                ("bdg1strycd", models.BigIntegerField(blank=True, null=True)),
                ("ward", models.BigIntegerField(blank=True, null=True)),
                ("policedist", models.BigIntegerField(blank=True, null=True)),
                ("zip", models.BigIntegerField(blank=True, null=True)),
                ("landuse", models.CharField(blank=True, max_length=254, null=True)),
                ("neighborho", models.CharField(blank=True, max_length=254, null=True)),
                ("zoning", models.CharField(blank=True, max_length=254, null=True)),
                ("sale", models.CharField(blank=True, max_length=254, null=True)),
                ("point_x", models.FloatField(blank=True, null=True)),
                ("point_y", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "StLouisCity_2022",
                "managed": False,
            },
        ),
    ]
