# Generated by Django 4.1.7 on 2023-04-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_alter_stlouiscitylandtax_neighborho"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lra2022",
            options={},
        ),
        migrations.RemoveField(
            model_name="stlouiscitylandtax",
            name="bdg1area",
        ),
        migrations.RemoveField(
            model_name="stlouiscitylandtax",
            name="bdg1year",
        ),
        migrations.RemoveField(
            model_name="stlouiscitylandtax",
            name="frontage",
        ),
        migrations.RemoveField(
            model_name="stlouiscitylandtax",
            name="landarea",
        ),
    ]
