from django.db import models


class LRAModel(models.Model):
    handle = models.CharField(max_length=16, blank=True, null=True, db_index=True)
    updated = models.DateField(blank=True, null=True, db_index=True)
    siteaddr = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    ownername = models.CharField(max_length=37, blank=True, null=True, db_index=True)
    ownername2 = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    owneraddr = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    ownercity = models.CharField(max_length=13, blank=True, null=True, db_index=True)
    ownerstate = models.CharField(max_length=2, blank=True, null=True, db_index=True)
    ownercntry = models.CharField(max_length=13, blank=True, null=True, db_index=True)
    ownerzip = models.CharField(max_length=9, blank=True, null=True, db_index=True)
    ownergroup = models.CharField(max_length=4, blank=True, null=True, db_index=True)
    numunits = models.IntegerField(blank=True, null=True, db_index=True)
    zoning1 = models.CharField(max_length=2, blank=True, null=True, db_index=True)
    zoning2 = models.CharField(max_length=2, blank=True, null=True, db_index=True)
    zoning3 = models.CharField(max_length=2, blank=True, null=True, db_index=True)
    vacantland = models.CharField(max_length=1, blank=True, null=True, db_index=True)
    asmtland = models.BigIntegerField(blank=True, null=True, db_index=True)
    asmtimprov = models.BigIntegerField(blank=True, null=True, db_index=True)
    asmttotal = models.BigIntegerField(blank=True, null=True, db_index=True)
    landuse1 = models.IntegerField(blank=True, null=True, db_index=True)
    landuse2 = models.IntegerField(blank=True, null=True, db_index=True)
    landuse3 = models.IntegerField(blank=True, null=True, db_index=True)
    landuse4 = models.IntegerField(blank=True, null=True, db_index=True)
    asruse1 = models.IntegerField(blank=True, null=True, db_index=True)
    asruse2 = models.IntegerField(blank=True, null=True, db_index=True)
    asruse3 = models.IntegerField(blank=True, null=True, db_index=True)
    asruse4 = models.IntegerField(blank=True, null=True, db_index=True)
    asrclass1 = models.IntegerField(blank=True, null=True, db_index=True)
    asrclass2 = models.IntegerField(blank=True, null=True, db_index=True)
    asrclass3 = models.IntegerField(blank=True, null=True, db_index=True)
    asrclass4 = models.IntegerField(blank=True, null=True, db_index=True)
    legal1 = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    legal2 = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    legal3 = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    legal4 = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    legal5 = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    numbldgs = models.IntegerField(blank=True, null=True, db_index=True)
    landarea = models.IntegerField(blank=True, null=True, db_index=True)
    frontage = models.FloatField(blank=True, null=True, db_index=True)
    dailydate = models.DateField(blank=True, null=True, db_index=True)
    dailynum = models.CharField(max_length=7, blank=True, null=True, db_index=True)
    booknum = models.CharField(max_length=4, blank=True, null=True, db_index=True)
    bookpage = models.CharField(max_length=4, blank=True, null=True, db_index=True)
    bdg1year = models.IntegerField(blank=True, null=True, db_index=True)
    bdg1area = models.IntegerField(blank=True, null=True, db_index=True)
    bdg1exwall = models.IntegerField(blank=True, null=True, db_index=True)
    bdg1strycd = models.IntegerField(blank=True, null=True, db_index=True)
    bdg1occcd = models.IntegerField(blank=True, null=True, db_index=True)
    cityblock = models.FloatField(blank=True, null=True, db_index=True)
    parcel = models.FloatField(blank=True, null=True, db_index=True)
    parity = models.CharField(max_length=1, blank=True, null=True, db_index=True)
    addrnum = models.IntegerField(blank=True, null=True, db_index=True)
    addrsuf = models.CharField(max_length=2, blank=True, null=True, db_index=True)
    streetpre = models.CharField(max_length=2, blank=True, null=True, db_index=True)
    streetname = models.CharField(max_length=30, blank=True, null=True, db_index=True)
    streetsuf = models.CharField(max_length=4, blank=True, null=True, db_index=True)
    strsufdir = models.CharField(max_length=2, blank=True, null=True, db_index=True)
    unitnum = models.CharField(max_length=10, blank=True, null=True, db_index=True)
    cdadist = models.IntegerField(blank=True, null=True, db_index=True)
    cdasubdist = models.IntegerField(blank=True, null=True, db_index=True)
    ward = models.IntegerField(blank=True, null=True, db_index=True)
    precinct02 = models.IntegerField(blank=True, null=True, db_index=True)
    precinct04 = models.IntegerField(blank=True, null=True, db_index=True)
    nbrhd = models.IntegerField(blank=True, null=True, db_index=True)
    asrnbrhd = models.IntegerField(blank=True, null=True, db_index=True)
    censblock = models.CharField(max_length=9, blank=True, null=True, db_index=True)
    policedist = models.IntegerField(blank=True, null=True, db_index=True)
    zip = models.CharField(max_length=5, blank=True, null=True, db_index=True)
    impactarea = models.IntegerField(blank=True, null=True, db_index=True)
    hsconserv = models.IntegerField(blank=True, null=True, db_index=True)
    ownerocc = models.CharField(max_length=1, blank=True, null=True, db_index=True)
    vacbldgyr = models.IntegerField(blank=True, null=True, db_index=True)
    parcel10 = models.BigIntegerField(blank=True, null=True, db_index=True)
    centract10 = models.FloatField(blank=True, null=True, db_index=True)
    cenblock10 = models.IntegerField(blank=True, null=True, db_index=True)
    ward10 = models.IntegerField(blank=True, null=True, db_index=True)
    precinct10 = models.IntegerField(blank=True, null=True, db_index=True)
    insparea10 = models.IntegerField(blank=True, null=True, db_index=True)
    leafarea = models.IntegerField(blank=True, null=True, db_index=True)
    blockpart = models.FloatField(blank=True, null=True, db_index=True)
    asrparcel = models.CharField(max_length=12, blank=True, null=True, db_index=True)
    centract20 = models.FloatField(blank=True, null=True, db_index=True)
    cenblock20 = models.IntegerField(blank=True, null=True, db_index=True)
    ward20 = models.IntegerField(blank=True, null=True, db_index=True)
    precinct20 = models.IntegerField(blank=True, null=True, db_index=True)
    insparea20 = models.IntegerField(blank=True, null=True, db_index=True)
    landuse = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    zoning = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    neighborho = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    point_x = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True, db_index=True)
    point_y = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True, db_index=True)

    class Meta:
        managed = False
        db_table = '2023_05_01_LRA'


class StLouisCityLandTax(models.Model):
    land_id = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    owner = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    address = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    total = models.FloatField(blank=True, null=True, db_index=True)
    handle = models.CharField(max_length=16, blank=True, null=True, db_index=True)
    numunits = models.BigIntegerField(blank=True, null=True, db_index=True)
    vacantland = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    numbldgs = models.BigIntegerField(blank=True, null=True, db_index=True)
    bdg1strycd = models.BigIntegerField(blank=True, null=True, db_index=True)
    ward = models.BigIntegerField(blank=True, null=True, db_index=True)
    policedist = models.BigIntegerField(blank=True, null=True, db_index=True)
    zip = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    landuse = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    neighborho = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    zoning = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    sale = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    point_x = models.FloatField(blank=True, null=True, db_index=True)
    point_y = models.FloatField(blank=True, null=True, db_index=True)

    class Meta:
        managed = False
        db_table = 'StLouisCity_2022'
